ReadRssFeeds.WebUI/Models/FeedsRSSList.cs
using ReadRssFeeds.DataProvider.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReadRssFeeds.WebUI.Models
{
    public class FeedsRSSList
    {
        public IEnumerable<NewsItem> feedsRss { get; set; }
        public SelectList resurseRSS { get; set; }
    }
}

ReadRssFeeds.WebUI/Controllers/ResurseRSSController.cs
using ReadRssFeeds.DataProvider.Abstract;
using ReadRssFeeds.DataProvider.Entities;
using ReadRssFeeds.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReadRssFeeds.WebUI.Controllers
{
    public class ResurseRSSController : Controller
    {
        private IResurseRSSRepository repository;

        public ResurseRSSController(IResurseRSSRepository itemRepository)
        {
            this.repository = itemRepository;
        }

        public ActionResult List(int? id, string sort)
        {
            List<NewsItem> feedRssList = repository.GetItemsAll().OrderByDescending(w => w.PublicDate).ToList();

            if (id != null && id != 0)
                feedRssList = feedRssList.Where(w => w.ResurseRSSId == id).ToList();

            if (!String.IsNullOrEmpty(sort) && sort.Equals("resurse"))
                feedRssList = feedRssList.OrderByDescending(w => w.ResurseRSSId).ToList();

            List<ResurseRSS> res = repository.GetResourceRSS;
            res.Insert(0, new ResurseRSS { Name = "Все", Id = 0 });

            FeedsRSSList feeds = new FeedsRSSList
            {
                feedsRss = feedRssList,
                resurseRSS = new SelectList(res, "Id", "Name")
            };
            return View(feeds);
        }

        public ActionResult List2(int? id, string sort = "resurse")
        {
            List<NewsItem> feedRssList = repository.GetItemsAll().OrderByDescending(w => w.PublicDate).ToList();

            if (id != null && id != 0)
                feedRssList = feedRssList.Where(w => w.ResurseRSSId == id).ToList();

            if (!String.IsNullOrEmpty(sort) && sort.Equals("resurse"))
                feedRssList = feedRssList.OrderByDescending(w => w.ResurseRSSId).ToList();

            if (Request.IsAjaxRequest())
                return PartialView("_item", feedRssList);

            List<ResurseRSS> res = repository.GetResourceRSS;
            res.Insert(0, new ResurseRSS { Name = "Все", Id = 0 });

            FeedsRSSList feeds = new FeedsRSSList
            {
                feedsRss = feedRssList,
                resurseRSS = new SelectList(res, "Id", "Name")
            };
            return View(feeds);
        }
    }
}

ReadRssFeeds.WebUI/Views/ResurseRSS/List.cshtml
@model ReadRssFeeds.WebUI.Models.FeedsRSSList

@{
    ViewBag.Title = "Reading RSS feeds";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Новостная лента</h2>

<form method="get">
    @Html.Partial("_form")
</form>

<table class="table">
    <tr>
        <th>Источник</th>
        <th>Название новости</th>
        <th>Описнаие новости</th>
        <th>Дата публикации</th>
    </tr>
    <tbody id="results">
        @Html.Partial("_item", Model.feedsRss)
    </tbody>

</table>

ReadRssFeeds.WebUI/Views/ResurseRSS/List2.cshtml
@using System.Web.Optimization
@model ReadRssFeeds.WebUI.Models.FeedsRSSList

@{
    ViewBag.Title = "Ajax";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts{
    @Scripts.Render("~/bundles/jqueryajax")
}

<h2>Новостная лента</h2>

@using (Ajax.BeginForm("List2", "ResurseRSS", new AjaxOptions { UpdateTargetId = "results" }))
{
    @Html.Partial("_form")
}

<table class="table">
    <tr>
        <th>Источник</th>
        <th>Название новости</th>
        <th>Описнаие новости</th>
        <th>Дата публикации</th>
    </tr>
    <tbody id="results">
        @Html.Partial("_item", Model.feedsRss)
    </tbody>
</table>

ReadRssFeeds.WebUI/Views/ResurseRSS/_form.cshtml
<div class="form-group">
    <label class="control-label col-md-2">Источник ленты </label>
    <div class="col-md-2">
        @Html.DropDownList("id", Model.resurseRSS as SelectList,
        htmlAttributes: new { @class = "form-control" })
    </div>
</div>
<div class="form-group">
    <div class="col-md-10">
        <div class="form-check">
            <label class="form-check-label">
                @Html.RadioButton("sort", "date", true)
                Сортировать по дате
            </label>

            <label class="form-check-label">
                @Html.RadioButton("sort", "resurse")
                Сортировать по источнику
            </label>
        </div>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-10">
        <input type="submit" class="btn btn-default" value="Просмотреть" />
    </div>
</div>

ReadRssFeeds.WebUI/Views/ResurseRSS/_item.cshtml
@model IEnumerable<ReadRssFeeds.DataProvider.Entities.NewsItem>

@if (Model.FirstOrDefault() != null)
{
    foreach (var item in Model)
    {
            <tr>
                <td>@Html.DisplayFor(model => item.ResurseRSS.Name)</td>
                <td>@Html.DisplayFor(model => item.Title)</td>
                <td>@Html.DisplayFor(model => item.Description)</td>
                <td>@Html.DisplayFor(model => item.PublicDate)</td>
            </tr>
    }
}

ReadRssFeeds.WebUI/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")
    @RenderSection("Style", false)
</head>
<body>
    <div>
        @RenderBody()


        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")

        @RenderSection("Scripts", required: false)
    </div>
</body>
</html>